name       : python-atomicwrites
version    : 1.2.1
release    : 1
source     :
    - https://github.com/untitaker/python-atomicwrites/archive/1.2.1.tar.gz : 84988f6ad66518546296ad002ed0e440560af7bfdeccb0b0e14672e6d71b0dc3
license    : MIT
component  : programming.python
summary    : Powerful Python library for atomic file writes
description: |
    Powerful Python library for atomic file writes
builddeps  :
    - python-setuptools
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
