name       : python-atomicwrites
version    : 1.4.0
release    : 7
source     :
    - https://github.com/untitaker/python-atomicwrites/archive/1.4.0.tar.gz : 47e897bea4ffdd4c0bc5f95b9417c1b4a661671b8a5abbefa05fbb344e83296e
license    : MIT
component  : programming.python
summary    : Powerful Python library for atomic file writes
description: |
    Powerful Python library for atomic file writes
builddeps  :
    - python-setuptools
    - python2-pytest
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
