name       : python-atomicwrites
version    : 1.3.0
release    : 3
source     :
    - https://github.com/untitaker/python-atomicwrites/archive/1.3.0.tar.gz : e286509543a26777e8cb862c9373e89c31f66fe38066d0df7f678d00a97615cd
license    : MIT
component  : programming.python
summary    : Powerful Python library for atomic file writes
description: |
    Powerful Python library for atomic file writes
builddeps  :
    - python-setuptools
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test py.test
#    %python3_test py.test3
